import type { TranslationAudioCatalog, TranslationAudioVoiceCatalog } from '../types';

export const BSB_AUDIO_BOOK_SLUGS: Record<string, string> = {
  GEN: 'Gen',
  EXO: 'Exo',
  LEV: 'Lev',
  NUM: 'Num',
  DEU: 'Deu',
  JOS: 'Jos',
  JDG: 'Jdg',
  RUT: 'Rut',
  '1SA': '1Sa',
  '2SA': '2Sa',
  '1KI': '1Ki',
  '2KI': '2Ki',
  '1CH': '1Ch',
  '2CH': '2Ch',
  EZR: 'Ezr',
  NEH: 'Neh',
  EST: 'Est',
  JOB: 'Job',
  PSA: 'Psa',
  PRO: 'Pro',
  ECC: 'Ecc',
  SNG: 'Sng',
  ISA: 'Isa',
  JER: 'Jer',
  LAM: 'Lam',
  EZK: 'Ezk',
  DAN: 'Dan',
  HOS: 'Hos',
  JOL: 'Jol',
  AMO: 'Amo',
  OBA: 'Oba',
  JON: 'Jon',
  MIC: 'Mic',
  NAM: 'Nam',
  HAB: 'Hab',
  ZEP: 'Zep',
  HAG: 'Hag',
  ZEC: 'Zec',
  MAL: 'Mal',
  MAT: 'Mat',
  MRK: 'Mrk',
  LUK: 'Luk',
  JHN: 'Jhn',
  ACT: 'Act',
  ROM: 'Rom',
  '1CO': '1Co',
  '2CO': '2Co',
  GAL: 'Gal',
  EPH: 'Eph',
  PHP: 'Php',
  COL: 'Col',
  '1TH': '1Th',
  '2TH': '2Th',
  '1TI': '1Ti',
  '2TI': '2Ti',
  TIT: 'Tts',
  PHM: 'Phm',
  HEB: 'Heb',
  JAS: 'Jas',
  '1PE': '1Pe',
  '2PE': '2Pe',
  '1JN': '1Jn',
  '2JN': '2Jn',
  '3JN': '3Jn',
  JUD: 'Jud',
  REV: 'Rev',
} as const;

export const BSB_AUDIO_VOICE_CATALOG: TranslationAudioVoiceCatalog = {
  defaultVoiceId: 'souer',
  voices: [
    {
      id: 'gilbert',
      label: 'Jordan Scott Gilbert',
      flag: {
        countryCode: 'US',
        emoji: '🇺🇸',
      },
      chapterFilenameSuffix: '_G',
    },
    {
      id: 'hays',
      label: 'Barry Hays',
      flag: {
        countryCode: 'US',
        emoji: '🇺🇸',
      },
      chapterFilenameSuffix: '_H',
    },
    {
      id: 'souer',
      label: 'Bob Souer',
      flag: {
        countryCode: 'US',
        emoji: '🇺🇸',
      },
    },
  ],
};

export const BSB_AUDIO_CATALOG: TranslationAudioCatalog = {
  strategy: 'voice-catalog',
  baseUrl: 'https://openbible.com/audio',
  fileExtension: 'mp3',
  mimeType: 'audio/mpeg',
  voiceCatalog: BSB_AUDIO_VOICE_CATALOG,
};

export function getBsbAudioBookSlug(bookId: string): string | null {
  return BSB_AUDIO_BOOK_SLUGS[bookId] ?? null;
}
