/**
 * Verse timestamp service — provides exact verse start times for audio follow-along.
 *
 * Timestamps are in SECONDS (float).
 * expo-av's currentPosition is in MILLISECONDS — divide by 1000 before comparing.
 *
 * Example:
 *   const timestamps = await getChapterTimestamps('web', 'GEN', 1);
 *   // timestamps[1] = 0.0, timestamps[2] = 4.2, ...
 *   // In bibleReaderModel getEstimatedFollowAlongVerse:
 *   //   timestamps[vn] <= currentPosition / 1000
 *
 * Files are bundled at: assets/timestamps/<TRANSLATION_UPPER>/<BOOK>_<CHAPTER_PADDED>.json
 * Generated by: npm run generate-timestamps -- --translation web
 *
 * Phase 14 note: this interface is stable for future remote URL loading.
 * When backend-driven timestamps are available, replace the require() path
 * with a fetch call without changing the return type or callers.
 */

export type VerseTimestamps = Record<number, number>;

// Static require map for Metro bundler — Metro needs static string paths.
// We build this map at module load time. Unknown chapters return null.
// Keys: "<TRANSLATION_UPPER>/<BOOK>_<CHAPTER_PADDED>"
type TimestampRequireFn = () => Record<string, number>;

const TIMESTAMP_REQUIRES: Record<string, TimestampRequireFn> = {
  // WEB timestamps — generated by: npm run generate-timestamps -- --translation web
  // BSB timestamps — generated by: npm run generate-timestamps -- --translation bsb
  // This map is intentionally empty until timestamp files are generated.
  // Once generated, add entries like:
  //   'WEB/GEN_001': () => require('../../assets/timestamps/WEB/GEN_001.json'),
  // The batch generator will print a code-gen snippet to add here.
};

/**
 * Returns verse timestamps for a given chapter, or null if not available.
 *
 * translationId: 'web' | 'bsb' (lowercase, matches translation IDs in the app)
 * bookId: 3-letter book ID e.g. 'GEN', 'MAT', '1CO' (matches src/constants/books.ts)
 * chapter: 1-indexed chapter number
 *
 * Falls back to word-weight estimation in bibleReaderModel when null is returned.
 */
export async function getChapterTimestamps(
  translationId: string,
  bookId: string,
  chapter: number
): Promise<VerseTimestamps | null> {
  try {
    const chapterPadded = String(chapter).padStart(3, '0');
    const key = `${translationId.toUpperCase()}/${bookId}_${chapterPadded}`;
    const requireFn = TIMESTAMP_REQUIRES[key];

    if (!requireFn) {
      return null;
    }

    const raw = requireFn() as Record<string, number>;

    // Convert string keys to number keys (JSON keys are always strings)
    const result: VerseTimestamps = {};
    for (const [k, v] of Object.entries(raw)) {
      const verseNum = Number(k);
      if (!Number.isNaN(verseNum) && typeof v === 'number') {
        result[verseNum] = v;
      }
    }

    return Object.keys(result).length > 0 ? result : null;
  } catch {
    // Gracefully return null if asset is missing or malformed
    return null;
  }
}

/**
 * Returns true if timestamps are available for a translation.
 * Use to conditionally show follow-along UI affordances.
 */
export function hasTimestampsForTranslation(translationId: string): boolean {
  const prefix = `${translationId.toUpperCase()}/`;
  return Object.keys(TIMESTAMP_REQUIRES).some((key) => key.startsWith(prefix));
}
